name: Publish Geoip data

on:
  workflow_dispatch:
  schedule:
    - cron: '0 22 * * *'

env:
  GEOIP_SOURCE_REPO: '8bitsaver/ipinfo-geoip-maxmind-compat'
  SINGBOX_SOURCE_REPO: 'sagernet/sing-box'
  SINGBOX_VER: '1.8.4'

jobs:
  run:
    name: Geoip database and rule-set
    runs-on: ubuntu-latest
    steps:
      - name: Prepare
        run: |
          echo "TAG_NAME=$(date +%Y%m%d%H%M%S)" >> $GITHUB_ENV
      
      - name: Checkout Source code
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
          path: './'

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.21"
          check-latest: true

      - name: Setup Python3
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install Python dependencies
        run: |
          python3 -m pip install httpx[http2]

      - name: Download sing-box
        run: |
          cd ${{ github.workspace }}
          curl --connect-timeout 5 --retry 5 --retry-delay 5 --retry-max-time 25 -sLo sing-box.tar.gz https://github.com/${{ env.SINGBOX_SOURCE_REPO }}/releases/download/v${{ env.SINGBOX_VER }}/sing-box-${{ env.SINGBOX_VER }}-linux-amd64v3.tar.gz
          tar xzvf sing-box.tar.gz --strip-components=1 -C ./
          chmod +x sing-box

      - name: Download country.mmdb
        run: |
          cd ${{ github.workspace }}
          curl --connect-timeout 5 --retry 5 --retry-delay 5 --retry-max-time 25 -sLo country.mmdb https://github.com/${{ env.GEOIP_SOURCE_REPO }}/releases/latest/download/country.mmdb
      
      - name: Generate sing-box geoip.db and its rule-set
        run: |
          cd ${{ github.workspace }}/sing-geoip
          go run ./ --mmdb-in ${{ github.workspace }}/country.mmdb --sdb-out ${{ github.workspace }} --srs-out ${{ github.workspace }}
      
      # Be careful, File geoip-de.json is 210.49 MB; this exceeds GitHub's file size limit of 100.00 MB
      - name: Export sing-box geoip rule-set json
        run: |
          cd ${{ github.workspace }}
          list=($(./sing-box geoip list -f ${{ github.workspace }}/geoip.db))
          echo "geoip node: ${#list[@]}"
          for ((i = 0; i < ${#list[@]}; i++)); do
            echo "write ${{ github.workspace }}/rule-set/geoip-${list[i]}.json"
            ${{ github.workspace }}/sing-box geoip export ${list[i]} -f ${{ github.workspace }}/geoip.db -o ${{ github.workspace }}/rule-set/geoip-${list[i]}.json
          done

      - name: Move rule-set country into another folder
        run: |
          mkdir -p ${{ github.workspace }}/rule-set/country
          mv ${{ github.workspace }}/rule-set/*.json ${{ github.workspace }}/rule-set/country
          mv ${{ github.workspace }}/rule-set/*.srs ${{ github.workspace }}/rule-set/country

      - name: Prepare for Company Geoip
        run: |
          mkdir -p ${{ github.workspace }}/rule-set/company

      - name: Fetch Company Geoip
        run: |
          cd ${{ github.workspace }}/rule-set/company
          python3 ${{ github.workspace }}/scripts/geoip-company/geoip-cloudflare.py
          python3 ${{ github.workspace }}/scripts/geoip-company/geoip-cloudfront.py
          python3 ${{ github.workspace }}/scripts/geoip-company/geoip-fastly.py
          python3 ${{ github.workspace }}/scripts/geoip-company/geoip-google.py
          python3 ${{ github.workspace }}/scripts/geoip-company/geoip-googlecloud.py
          python3 ${{ github.workspace }}/scripts/geoip-company/geoip-telegram.py
          python3 ${{ github.workspace }}/scripts/geoip-company/geoip-github.py

      - name: Generate rule-set binary
        run: |
          cd ${{ github.workspace }}/rule-set/company
          ${{ github.workspace }}/sing-box rule-set compile ${{ github.workspace }}/rule-set/company/geoip-cloudflare.json
          ${{ github.workspace }}/sing-box rule-set compile ${{ github.workspace }}/rule-set/company/geoip-cloudfront.json
          ${{ github.workspace }}/sing-box rule-set compile ${{ github.workspace }}/rule-set/company/geoip-fastly.json
          ${{ github.workspace }}/sing-box rule-set compile ${{ github.workspace }}/rule-set/company/geoip-google.json
          ${{ github.workspace }}/sing-box rule-set compile ${{ github.workspace }}/rule-set/company/geoip-googlecloud.json
          ${{ github.workspace }}/sing-box rule-set compile ${{ github.workspace }}/rule-set/company/geoip-telegram.json
          ${{ github.workspace }}/sing-box rule-set compile ${{ github.workspace }}/rule-set/company/geoip-github.json

      - name: Generate geoip/mmdb sha256 hash
        run: |
          cd ${{ github.workspace }}
          sha256sum geoip.db > ${{ github.workspace }}/geoip.db.sha256sum
          sha256sum geoip-cn.db > ${{ github.workspace }}/geoip-cn.db.sha256sum

      - name: Push to "release" branch
        run: |
          mkdir -p ${{ github.workspace }}/release-upload
          cp ${{ github.workspace }}/geoip.db ${{ github.workspace }}/release-upload/
          cp ${{ github.workspace }}/geoip-cn.db ${{ github.workspace }}/release-upload/
          cp ${{ github.workspace }}/geoip.db.sha256sum ${{ github.workspace }}/release-upload/
          cp ${{ github.workspace }}/geoip-cn.db.sha256sum ${{ github.workspace }}/release-upload/
          cd ${{ github.workspace }}/release-upload
          git init
          git config user.name "Epsilon"
          git config user.email "${{ github.actor_id }}+${{ github.actor }}@users.noreply.github.com"
          git checkout -b release
          git add .
          git commit -m "${{ env.TAG_NAME }}"
          git remote add origin "https://${{ github.actor }}:${{ github.token }}@github.com/${{ github.repository }}"
          git push -f origin release

      - name: Push to "rule-set" branch
        run: |
          cd ${{ github.workspace }}/rule-set
          git init
          git config user.name "Epsilon"
          git config user.email "${{ github.actor_id }}+${{ github.actor }}@users.noreply.github.com"
          git checkout -b rule-set
          git add .
          git commit -m "${{ env.TAG_NAME }}"
          git remote add origin "https://${{ github.actor }}:${{ github.token }}@github.com/${{ github.repository }}"
          git push -f origin rule-set

      - name: Upload to Releases
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          tag_name: ${{ env.TAG_NAME }}
          body: ${{ env.TAG_NAME }}
          draft: false
          prerelease: false
          files: |
            ${{ github.workspace }}/geoip.db*
            ${{ github.workspace }}/geoip-cn.db*

      - name: Remove old Releases
        uses: dev-drprasad/delete-older-releases@v0.3.2
        with:
          keep_latest: 3
          delete_tags: true
        env:
          GITHUB_TOKEN: ${{ github.token }}

      # - name: Upload to Latest Tag
      #   uses: softprops/action-gh-release@v1
      #   env:
      #     GITHUB_TOKEN: ${{ github.token }}
      #   with:
      #     tag_name: latest
      #     body: The latest.
      #     draft: false
      #     prerelease: true
      #     files: |
      #       ${{ github.workspace }}/geoip.db*
      #       ${{ github.workspace }}/geoip-cn.db*

      - name: Remove old Workflow runs records
        uses: Mattraks/delete-workflow-runs@v2
        with:
          token: ${{ github.token }}
          repository: ${{ github.repository }}
          retain_days: 3
          keep_minimum_runs: 3
